### ISSUE TITLE
Implement a memory layout inside the arena

### ISSUE THREAD

**Issue by dulvinw** [lk-hpc/ffm_mpi_distributed_matrix#2]
## Requirements

1. Investigate how to use java FFM to create data layout inside the `Arena`
2. Implement memory layout in java
3. Implement memory layout mapping in c++

**Comment by gihanlaks** [comment]
Memory Segments created when Matrix object initializes. Then getAddress, getByteSize methods can be used to pass the information to cpp side to read the memory segment from there and extract vector 2d array from cpp side.
